name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    uses: mih-kopylov/workflows/.github/workflows/build.yml@master
    with:
      docker: true
