name: release
on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-release:
    uses: mih-kopylov/workflows/.github/workflows/release.yml@master
