name: update-dependencies
on:
  push:
    branches:
      - pat
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  update-dependencies:
    uses: mih-kopylov/workflows/.github/workflows/update-dependencies.yml1@pat
    with:
      token: ${{ secrets.UPDATE_DEPENDENCIES_PAT }}
