name: update-dependencies
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.UPDATE_DEPENDENCIES_PAT }}
      - name: Configure golang
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Update dependencies
        run: |
          go get -u -t ./...
          go mod tidy
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.UPDATE_DEPENDENCIES_PAT }}
          commit-message: "[CI] Update dependencies"
          branch: update-dependencies
          delete-branch: true
          title: "[CI] Update dependencies"
